-- COPY TOÀN BỘ VÀ CHẠY TRONG SUPABASE SQL EDITOR

-- 1. Create Table Manager
create table if not exists public.table_manager (
  id bigint generated by default as identity primary key,
  table_number int not null unique,
  status text check (status in ('available', 'occupied', 'reserved', 'paused')) default 'available',
  player_name text,
  player_count int default 2,
  start_time timestamptz,
  services jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- Disable RLS for easy access (or configure policies if you prefer)
alter table public.table_manager disable row level security;

-- 2. Create Transactions Table
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  category_id int, 
  amount numeric not null,
  description text,
  transaction_date timestamptz default now(),
  created_by uuid references auth.users(id),
  is_active boolean default true,
  created_at timestamptz default now()
);
alter table public.transactions disable row level security;

-- 3. Create Coaches Table
create table if not exists public.coaches (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  fee text, 
  table_fee text,
  color text,
  created_at timestamptz default now()
);
alter table public.coaches disable row level security;

-- 4. Create Training Sessions Table
create table if not exists public.training_sessions (
  id bigint generated by default as identity primary key,
  day text not null, 
  start_time text, 
  end_time text, 
  coach_id bigint references public.coaches(id),
  location text, 
  created_at timestamptz default now()
);
alter table public.training_sessions disable row level security;

-- 5. Auto-Generate 15 Tables (Data Seeding)
-- Chỉ chạy dòng này nếu bảng chưa có dữ liệu
insert into public.table_manager (table_number, status, services) 
select i, 'available', '[]'::jsonb 
from generate_series(1, 15) as i
on conflict (table_number) do nothing;
